version: '3'
services:
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - .:/app
    depends_on:
      - php-fpm
    ports:
      - "8080:80"
  php-fpm:
    build:
      context: ./docker/php
      dockerfile: php-fpm.docker
    environment:
      PHP_IDE_CONFIG: serverName=laravel-starter-kit-api
    volumes:
      - .:/app
    depends_on:
      - db
  php-cli:
    build:
      context: ./docker/php
      dockerfile: php-cli.docker
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mysql:8
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel_starter_kit_api
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3306:3306"
volumes:
  db:
